### ISSUE TITLE
Referenzseiten

### ISSUE THREAD

**Issue by hfd** [hfd/Relaunch#1]
Wäre es möglich, eine Liste von Referenzseiten zu haben. Gute Beispiele von Referenzseiten, die in dieser Liste aufgeführt werden könnten, sind die Startseite von LT sowie die Personalseite von LT.

Wünschenswert sind Referenzseiten für:
- Seite(n) eines Studiengangs
- Inhaltsseite eines Fachbereichs (Seite mit Titel, Text, Bild)
- Seite mit Bildergalerie

**Comment by paulgrimm** [comment]
Bisherige Referenzseiten nach meinem Wissen

FB Startseite

![image](https://cloud.githubusercontent.com/assets/6088213/9899255/ed7d0f6c-5c58-11e5-9cf0-13e97600d32e.png)

Personalseite
![image](https://cloud.githubusercontent.com/assets/6088213/9899305/3ea60e7a-5c59-11e5-96c8-3acb129d408d.png)

**Comment by paulgrimm** [comment]
Auf der Fachbereichsstartseite von LT fehlt das "Jetzt bewerben"

**Comment by paulgrimm** [comment]
Auf der Personalseite fehlt der Titel der Seite. Eigentlich hätte ich etwas erwartet als Titel wie "Professorinnen und Professoren des Fachbereichs LT (Zitat der jetzigen Personalseite)
![image](https://cloud.githubusercontent.com/assets/6088213/9904531/cd700f64-5c7e-11e5-9431-b24c11e1e223.png)

**Comment by 1mheinz** [comment]
Hallo,

soweit ich weiß ist der Button aktuell ein Provisorium. Er wird nur angezeigt, wenn eine E-Mail Adresse im Feld "Linkziel" eingetragen ist. Das ist bei der LT Seite nicht der Fall, deshalb ist er im Code vorhanden, wird aber im Frontend nicht gezeigt.

Zum Thema Seitenname eine Ergänzung: Im Tab wird aktuell als Name jeder Seite "Navigationsmenüpunktname - fh-fulda.de" angezeigt. Das ist aber auch ein Provisorium wie ich vermute.
