### ISSUE TITLE
Einzelne Personalseiten fehlen im Menü: Zugriff auf Beschäftigtenprofile nur über Kachelanzeige?

### ISSUE THREAD

**Issue by 1mheinz** [hfd/Relaunch#12]
Aktuell ist der Zugriff auf ein Dozentenprofil/Mitarbeiterprofil nur über die Kachelansichtseite möglich.
Wird ein Direktzugriff aus der linksseitigen Navigation ermöglicht werden?
Wird ein "nächster MitarbeiterIn/ProfessorIn" Durchklicken bei der Anzeige der Profile ermöglicht werden? (Aktuell sind es jeweils drei Klicks, um Profile nacheinander durchzugehen, pro Profil).

**Comment by paulgrimm** [comment]
Zum Vergleich, wie es auf der alten Seite gut umgesetzt war

![image](https://cloud.githubusercontent.com/assets/6088213/9898954/e6cbf752-5c56-11e5-99fe-bbbd1b172600.png)
