### ISSUE TITLE
Hochformat erzeugt Probleme im Seitenkopf

### ISSUE THREAD

**Issue by hfd** [hfd/Relaunch#2]
Beispielhafte Probleme
- Suchfeld überlagert Kontakt
- "Zum Blog" ist in zweiter Zeile

**Comment by paulgrimm** [comment]
![image](https://cloud.githubusercontent.com/assets/6088213/9898849/0628b316-5c56-11e5-9a04-338c405c36bf.png)

**Comment by paulgrimm** [comment]
Man sieht auch, dass der linke Rand teilweise die Größe 0pt hat (z.B. beim Logo und bei der Überschrift Angewandte Informatik)

**Comment by paulgrimm** [comment]
Hier die Darstellung der Personalseite

![image](https://cloud.githubusercontent.com/assets/6088213/10069847/20cb65d8-62af-11e5-8a1d-d382bd0378d4.png)

**Comment by paulgrimm** [comment]
Und hier die Druckansicht mit Trauerrahmen der "Angewandte Jetzt bewerben"

![image](https://cloud.githubusercontent.com/assets/6088213/10069878/4c9a34be-62af-11e5-9a63-afb7d6fea013.png)
