### ISSUE TITLE
Fehlen des Standardmenüs bei Anwahl Beschäftigtenprofil

### ISSUE THREAD

**Issue by 1mheinz** [hfd/Relaunch#7]
Wählt man z.B. ein ProfessorInnenprofil, so verschwindet die Standardnavigation links. Erst ein Klick auf "zurück zu Listenansicht" stellt diese wieder her.

Ist dies so gewollt?
Wird dies auch bei anderen Navigationspunkten so sein, oder ist dies bei den Beschäftigten eine Ausnahme?

**Comment by paulgrimm** [comment]
Der Wunsch des Fachbereichs ist es, dass auf allen Seiten des Fachbereichs immer das gleiche Menü auf der linken Seite zur Verfügung steht (entsprechend der Vorgaben mit Über uns, Studieninteressierte, Studium, Forschung, ...)

**Comment by paulgrimm** [comment]
![image](https://cloud.githubusercontent.com/assets/6088213/9899182/75f8279c-5c58-11e5-8711-31a6ade4c70c.png)

**Comment by paulgrimm** [comment]
Antwort von HK:

--> Das wird in diesem Seitenbereich so sein, da sich auf dieser Ebene
User über den Professor/die Professorin informieren wollen - bei anderen
Seiten wird dies anders sein. In GitHub hatten Sie noch eine
"Weiterklick"-Funktion erwähnt, darüber können wir nachdenken, hat
jedoch im jetzigen Stadium nicht die höchste Priorität.

**Comment by paulgrimm** [comment]
Aus dem Feedback meiner Kollegen höre ich immer wieder, dass das Suchen und Betrachten der Personalseiten elementar ist. 

Es ist daher nicht ersichtlich (außer aus technischen Gründen), dass diese Seiten nicht ganz normal im Menü eingebunden sind und somit eine normale Navigation erlauben. Navigationselemente wie "zurück" und "weiter" sind da nur Krücken.
